### ISSUE TITLE
Parse::CPAN::Meta 1.4418 (dev release) passes incorrect JSON args

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/Parse-CPAN-Meta#12] opened 2016-04-27 20:13 UTC
with https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Getopt-0.69.tar.gz:

```
: [ether@jaeger MooseX-Getopt/MooseX-Getopt-0.69]$; perl Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for MooseX::Getopt
Writing MYMETA.yml and MYMETA.json
```
(EUMM is happy)

```
: [ether@jaeger MooseX-Getopt/MooseX-Getopt-0.69]$; perl Build.PL
malformed UTF-8 character in JSON string, at character offset 47989 (before "\x{fffd}ar Arnfj\x{fffd}...") at /Volumes/amaretto/Users/ether/.perlbrew/libs/23.9@std/lib/perl5/Parse/CPAN/Meta.pm line 53.
 at /Volumes/amaretto/Users/ether/perl5/perlbrew/perls/23.9/lib/5.23.9/CPAN/Meta.pm line 301.
 at /Volumes/amaretto/Users/ether/.perlbrew/libs/23.9@std/lib/perl5/Module/Build/Tiny.pm line 33.
```
(Module::Build::Tiny is not)

My environment has: `PERL_JSON_BACKEND=Cpanel::JSON::XS`

**Comment by karenetheridge** [comment] 2016-04-27 20:16
Note that {*::}JSON::XS expects that files contain utf-8-encoded octets, not characters. Consequently either the file should be slurped raw and *not* decoded, or a {*::}JSON::XS object should be constructed with `utf8=>0` set.

**Comment by karenetheridge** [comment] 2016-04-27 21:28
This change is responsible:

```
-  my $data = eval { $class->json_backend()->new->decode($string) };
+  my $data = eval { $class->json_backend()->can('decode_json')->($string) };
```

`decode_json` is like `$backend->new(utf8=>1)`. The `->decode` call should be left alone as it was.

**Comment by haarg** [comment] 2016-04-27 22:54
The reason for the change was to allow modules like Mojo::JSON or JSON::Tiny to be used.  They don't provide an object oriented interface, so leaving it as `->new->decode` would be wrong.

**Comment by karenetheridge** [comment] 2016-04-28 00:06
We'll have to skip the utf8-decoding step then.  Will Mojo::JSON and JSON::Tiny be able to handle bytes rather than characters? If not, we'll need switches for the different backends.

**Comment by haarg** [comment] 2016-04-28 00:46
Mojo::JSON and JSON::Tiny always expect UTF-8 encoded bytes, just like the the decode_json routines in the other JSON modules.

**Comment by karenetheridge** [comment] 2016-04-28 03:31
example failures:

http://www.cpantesters.org/cpan/report/baa3f462-0af8-11e6-9d2d-a18020bbf307
http://www.cpantesters.org/cpan/report/65735436-0b2c-11e6-9d2d-a18020bbf307

**Comment by Leont** [comment] 2016-04-28 16:12
>  at /Volumes/amaretto/Users/ether/.perlbrew/libs/23.9@std/lib/perl5/Module/Build/Tiny.pm line 33.

That line is exactly: 
~~~
return CPAN::Meta->load_file($metafile);
~~~
If that kind of breakage wasn't noticed by the test-suite, we need better tests.

**Comment by shadowcat-mst** [comment] 2016-04-28 18:29
On Wed, Apr 27, 2016 at 01:16:32PM -0700, Karen Etheridge wrote:
> Note that {*::}JSON::XS expects that files contain utf-8-encoded octets, not characters. Consequently either the file should be slurped raw and *not* decoded, or a {*::}JSON::XS object should be constructed with `utf8=>0` set.

So it may be that we can only fix load_file rather than load_foo_string?

That might still be a net win.

-- 
Matt S Trout - Shadowcat Systems - Perl consulting with a commit bit and a clue

http://shadowcat.co.uk/blog/matt-s-trout/   http://twitter.com/shadowcat_mst/

Email me now on mst (at) shadowcat.co.uk and let's chat about how our CPAN
commercial support, training and consultancy packages could help your team.

**Comment by karenetheridge** [comment] 2016-04-28 19:17
`load_string` would work too if the characters were encoded to octets first before passing them to the json backend.

**Comment by Leont** [comment] 2016-04-28 20:18
> So it may be that we can only fix load_file rather than load_foo_string?

> That might still be a net win.

It seems very few people use load_json_string directly, a [cpan grep](http://grep.cpan.me/?q=load_json_string) gives mostly noise due to inclusion of CPAN::Meta but Pinto appears to be the only important thing that uses that function.

**Comment by karenetheridge** [comment] 2016-04-29 04:03
More failures:

https://rt.cpan.org/Ticket/Display.html?id=114060
http://www.cpantesters.org/cpan/report/5ec926b0-0b81-11e6-a317-839d20bbf307

**Comment by shadowcat-mst** [comment] 2016-04-29 19:42
I'm tempted to make load_file skip the decoding for JSON, and to make load_json_string re-encode what it's been passed before parsing it, and to add someting like load_encoded_json_string and load_encoded_yaml_string as well perhaps.

Code's easy enough - what are people's thoughts on that as an approach?

**Comment by haarg** [comment] 2016-04-29 21:34
Internally, when JSON::PP is decoding from a character string, it encodes to UTF-8 before processing the string.  So having Parse::CPAN::Meta do that instead should amount to the same thing at least for JSON::PP.

**Comment by shadowcat-mst** [comment] 2016-04-30 15:34
Right, reproduced the problem, added the encode, problem seems to have disappeared so I've sent another dev release on its way.

This is the smallest change possible because I'd rather not have the previous devrel 'on top' producing problems for devrel smokers; we can be more clever once we have a pope again. Leaving the issue open since I don't consider it actually fixed until at the very least I have tests for this.

**Comment by xdg** [comment] 2016-06-23 09:57
@shadowcat-mst, can we close this now?

**Comment by xdg** [comment] 2016-06-23 10:51
Particularly now that I've merged tests in 18154feccf67e7aa4ec1f9fa4a3ed444e0b83067 based on #8

**Comment by xdg** [comment] 2016-06-23 11:07
Oops.  Added back some tests in 8ea24a2

**Comment by xdg** [comment] 2016-06-23 11:08
I've shipped a devrel to see how these tests smoke, but I'd like to close this now that we have a fix and tests released.

**Comment by xdg** [comment] 2016-08-18 16:19
New PCM has shipped in CPAN::Meta.  Closing this ticket.

**Closed by xdg** 2016-08-18 16:19 UTC
